<?php
// module/Inventaire/view/inventaire/inventaire/index.phtml:

$title = 'Mon inventaire';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if (count($inventaires)):
	foreach (inventaires as $inventaire): ?>
 		 <li><?php var_dump($inventaire); ?></li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'my_pagination_control', array('route' => 'inventaire')); ?>