<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<div class="pagination pagination-mini">
  <ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="<?php echo $this->url($route, array('action'=>$action, 'page' => $this->previous)); ?>">
    &laquo;
  </a></li>
<?php else: ?>
  <li><a class="disabled">&laquo;</a></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $this->url($route, array('action'=>$action, 'page' => $page)); ?>">
        <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li><a class="active"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a href="<?php echo $this->url($route, array('action'=>$action, 'page' => $this->next)); ?>">
    &raquo;
  </a></li>
<?php else: ?>
  <li><a class="disabled">&raquo;</a></li>
<?php endif; ?>
  </ul>
</div>
<?php endif; ?>