<?php

$title = 'Récolement';
$this->headTitle($title);

?>
<div class="row">
	<div class="span6">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="span6">
		<span class="pull-right">
		<?php if ($auth["logged"]) { ?>
			<p>	
			<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(),array("img_size"=>24)) ?>
			<a href="/user"><?php print $auth["login"] ?></a>
			</p>
			<?php 
		} else {
			?>
			<p>
			Vous n'êtes pas identifié 
			<a class="btn btn-small btn-info" href="/">connexion</a>
			</p>
		<?php } ?>
		</span>
	</div>
</div>

<div class="row">
	<div class="span12">
	<P>Recolements : <?php print count($recolements);?></P>
	<?php foreach ($recolements as $recolement) :?>
		<p>Identifiant : <?php print $recolement->idno;?></p>
		<p>Titre : <?php print $recolement->display_label;?></p>
	<?php endforeach; ?>
	</div>
</div>
