<?php

//error_reporting(E_ALL);

$PHPWord = new PHPWord();
$document = $PHPWord->loadTemplate(getcwd().'/public/files/recolement/PV_recolement.docx');

// TITRE
$document->setValue('preferred_labels', utf8_decode($campagne->preferred_labels->fr_FR["0"]));

// DATES
$datefield = "ca_occurrences.date_campagne_c";
$datefield_content = $campagne->$datefield;
$datedebut = $datefield_content[0]->none->date_campagne_debut;
$datefin = $datefield_content[0]->none->date_campagne_fin;
$document->setValue('date_campagne', utf8_decode($datedebut." - ".$datefin));


// METHODE
$methodefield = "ca_occurrences.campagne_methode_c";
$methodefield_content = $campagne->$methodefield;
$campagne_caracteristiques = $methodefield_content[0]->none->campagne_caracteristiques;
$campagne_moyens = $methodefield_content[0]->none->campagne_moyens;
$methode_intervenant = $methodefield_content[0]->none->methode_intervenant;
$document->setValue('campagne_caracteristiques', utf8_decode($campagne_caracteristiques));
$document->setValue('campagne_moyens', utf8_decode($campagne_moyens));
$document->setValue('methode_intervenant', utf8_decode($methode_intervenant));

// CHAMP COUVERT
$champfield = "ca_occurrences.campagne_champs_c";
$champfield_content = $campagne->$champfield;
$campagne_champs_c = $champfield_content[0]->fr_FR;
$campagne_champs_champs = $campagne_champs_c->campagne_champs_champs;
$campagne_champs_note = $campagne_champs_c->campagne_champs_note;
$document->setValue('campagne_champs_champs', utf8_decode($campagne_champs_champs));
$document->setValue('campagne_champs_note', utf8_decode($campagne_champs_note));


//$document->setValue('weekday', date('l'));
//$document->setValue('time', date('H:i'));

$filename=getcwd()."/public/tmp/PV_recolement.docx";
if (is_file($filename)) unlink($filename);
$document->save($filename);

header('Content-Description: File Transfer');
header('Content-type: application/force-download');
header('Content-Disposition: attachment; filename='.basename($filename));
header('Content-Length: '.filesize($filename));
readfile($filename);﻿
?>