<?php
//Prepare Display options to fine tune the form presentation
//This is optional, your form can be rendered without any display options
$displayOptions = array(
    //The class attribute added to the form tag
    //'class'                 => 'my-form-class',
    'fieldsets'             => array(
        'fsOne'                 => array(
            //The class attribute added to the fieldset class
            //'class'             => 'my-fsOne-class',
            //Should the display legend be shown? (If this option is not defined, defaults to true.)
            'display_legend'        => true
            ),
        ),
        'fsTwo'                 => array(
        	'display_legend'        => true
        ),
    'elements'              => array(
		'numinv'                => array(
    		'class'                 => 'input-medium',
    		'prependIcon'           => 'icon-tag',
		    'required'              => true,
    		),
		'mode_acquisition'		=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
    	'donateur'		=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
    	'date_acquisition' 	=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'avis'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'prix'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
		'date_inscription'	=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
		'designation'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'inscription'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'materiaux'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'techniques'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'mesures'                => array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'etat'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'auteur'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'epoque'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
        'usage'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
		'provenance'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		),
		'observations'				=> array(
        		'class'             => 'ckeditor',
        		'rows'              => 3,
        		'required'          => false,
		)
	)
);
 
//Form object
$form           = $this->form;
$formType       = "horizontal";
$form->prepare();
if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Saisie invalide !</strong>
        Les champs du formulaire ne sont pas remplis correctement.
    </div>
<?php else: ?>
    <div class="alert alert-info">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Enregistrer</strong>
        Si certains champs ne contiennent pas des informations valides, ils seront mis en évidence.
    </div>
<?php
endif;
 
echo $this->formTwb($form, $formType, $displayOptions);

?> 
<script>
		$(function(){
			window.prettyPrint && prettyPrint();
		});
</script>
