<?php
// module/Inventaire/view/inventaire/inventaire/index.phtml:

$title = "Import d'un ensemble depuis la base CollectiveAccess";
$this->headTitle($title);

$ca_set_id = ( isset($ca_set_id) ? true : false );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(!$ca_set_id) :
?>
<div class="row">
	<div class="span12">
	<form action="<?php echo $this->url; ?>" method="post">
	    <div>
	    	<h3><label class="control-label required" for="ca_id">Identifiant interne CollectiveAccess de l'ensemble </label>
	    	<input type="text" name="set_id" /></h3>
	    </div>
	    <div>
	    	 <input type="submit" name="insert" value="Importer" class="btn btn-info btn-large" />
	    </div>
	</form>
	</div>
</div>

<?php else :?>

<div class="row">
	<div class="span12">
		<?php  foreach($result_imports as $key=>$result) : ?>
			<div class="row">
			<?php print ( $result_imports_photos[$key]["file"] ? "<img src=\"/files/assets/".$results_photos[$key]["file"]."\" style=\"max-height:40px;max-width:40px;float:left;margin:4px 10px 4px 32px;\">" : "[".$result_imports_photos[$key]["error"]."]" );?>
			<?php print "<p><b><a href=\"/inventaire/view/".$result["id"]."\">".$result["designation"]."</a></b> ".$result["numinv_display"]." (objet ".$key.")</p>";?>
			</div>
			<?php if(!isset($result["error"])) : ?>
				<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
					Import réussi 
				</div>
			<?php else : ?>
				<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">×</button>
					<?php print $result["error"];?>
				</div>
			<?php endif; ?>
		<?php endforeach; ?>
	</div> 
</div>
<?php endif;?>
<div class="row">
	<div class="span12">
		<p class="btn-group">
		    <a class="btn btn-info" href="<?php echo $this->url('inventaire', array());?>">Revenir à la liste des objets</a>
		</p>
	</div>
</div>