<?php
// module/Inventaire/view/inventaire/inventaire/index.phtml:

$title = 'Les collections';
$this->headTitle($title);

?>
<div class="row">
	<div class="span6">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="span6">
		<span class="pull-right">
		<?php if ($auth["logged"]) { ?>
			<p>	
			<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(),array("img_size"=>24)) ?>
			<a href="/user"><?php print $auth["login"] ?></a>
			</p>
			<?php 
		} else {
			?>
			<p>
			Vous n'êtes pas identifié 
			<a class="btn btn-small btn-info" href="/">connexion</a>
			</p>
		<?php } ?>
		</span>
	</div>
</div>

<div class="row">
	<div class="span12">
		<table class="table  table-striped  bord-ronds-fond-blanc">
		<tr>
		    <th><?php print $fieldsname["numinv"]; ?></th>
		    <th><?php print $fieldsname["designation"]; ?></th>
		    <th><?php print $fieldsname["auteur"]; ?></th>
		    <th><span class="pull-right">Actions</span></th>
		</tr>
		<?php foreach ($inventaires as $inventaire) : ?>
		<tr>
		    <td>
			    <?php if ($inventaire->file) : ?>
				    <span style="width:36px;height:36px;background:transparent;display:inline-block;text-align:center;">
				    	<a href="<?php print "/inventaire/view/".$this->escapeHtml($inventaire->id);?>" alt="Afficher" title="Afficher">
				    	<img style="height:30px;" src="/files/assets/<?php print $inventaire->file; ?>" align="absmiddle">
				    	</a>
				    </span>
			    <?php else : ?>
			    	<span>
			    		<a href="<?php print "/photo/add/".$this->escapeHtml($inventaire->id);?>" alt="Ajouter une photo" title="Ajouter une photo"><img src="/images/icone-image.png"  style="width:36px;" align="absmiddle"></a>
			    	</span>
			    <?php endif; ?>
			    <a href="<?php print "/inventaire/view/".$this->escapeHtml($inventaire->id);?>" alt="Afficher" title="Afficher"> 
			    <?php echo $this->escapeHtml($inventaire->numinv);?>
			    </a>
		    </td>
			<td>
				<?php echo $this->escapeHtml($inventaire->designation);?>
			</td>
			<td>
				<?php echo $this->escapeHtml($inventaire->auteur);?>
			</td>
			<td>
				<span class="pull-right">
					<div class="btn-group">
					<?php if($auth["logged"]) : ?>
						<?php if (!$inventaire->validated) : // Si l'enregistrement n'est pas validé, on peut le modifier ou le valider ?> 
							<a  class="btn btn-success btn-small" href="<?php echo $this->url('inventaire',
							array('action'=>'edit', 'id' => $inventaire->id));?>" title="Modifier"><i class="icon-pencil icon-white"></i></a>
				        	<a  class="btn btn-success btn-small" href="<?php echo $this->url('inventaire',
				            array('action'=>'delete', 'id' => $inventaire->id));?>" title="Supprimer"><i class="icon-remove icon-white"></i></a>
							<a  class="btn btn-warning btn-small" href="<?php echo $this->url('inventaire',
							array('action'=>'validate', 'id' => $inventaire->id));?>" title="Valider"><i class="icon-ok icon-white"></i></a>
						<?php else :?> 
							<a  class="btn disabled btn-small" title="Modifier"><i class="icon-pencil icon-white"></i></a>
							<a  class="btn disabled btn-small" title="Supprimer"><i class="icon-remove icon-white"></i></a>
							<a  class="btn disabled btn-small" title="Valider"><i class="icon-ok icon-white"></i></a>
						<?php endif; ?>
						<a  class="btn btn-success btn-small" href="<?php echo $this->url('inventaire',
							array('action'=>'export', 'id' => $inventaire->id));?>" title="Exporter vers CA"><i class="icon-share icon-white"></i></a>
					<?php endif; ?>
				</div>
			</span>
	    </td>
		</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div>
<div class="row">
	<div class="span6">
		<?php echo $this->paginationControl($inventaires,
                                    'Sliding',
                                    'inventaire/inventaire/my_pagination_control', array('route'=>'inventaire','action'=>'index'));?>
    </div>
    <div class="span6">
            <?php if (count($yearsOptions)>2) :?>
            	<span class="pull-right">
				 <div class="btn-group"><a class="btn btn-info btn-small" href="<?php print $this->url('inventaire');?>">Toutes les années</a>
				<?php foreach($yearsOptions as $option) : ?>
					<?php if((isset($option["disabled"]) && (!$option["disabled"]))) : ?> 
						<a class="btn btn-info btn-small" href="<?php print $this->url('inventaire', array('action'=>'index', 'annee'=> $option["label"]));?>"><?php print $option["label"] ?></a> 
					<?php endif ?>
				<?php endforeach ?>
				</div>
				</span>
            <?php endif ?>
	</div>
</div>
<?php 
if($auth["logged"]) {
?>
<div class="row">
	<div class="span6">
		<div class="btn-group">
		<a class="btn btn-success" href="<?php echo $this->url('inventaire', array('action'=>'add'));?>"><i class="icon-plus icon-white icon-large"></i> Ajouter un objet</a>
		<a class="btn btn-success" href="<?php echo $this->url('inventaire', array('action'=>'add'));?>"><i class="icon-circle-arrow-down icon-white icon-large"></i> Importer depuis CA</a>
		<a class="btn btn-success" href="<?php echo $this->url('inventaire', array('action'=>'listingExportPdf'));?>"><i class="icon-book icon-white icon-large"></i> Générer le PDF</a>
		<a class="btn btn-info" href="<?php echo $this->url('photo', array('action'=>'index'));?>"><i class="icon-camera icon-white icon-large"></i> Afficher les photos</a>
		</div>
	</div>
	<div class="span6">
		<span class="pull-right">
			<div class="btn-group">
			<a class="btn btn-success btn-small" href="<?php echo $this->url('inventaire', array('action'=>'listingExportCSV'));?>"><i class="icon-th icon-white"></i> Export tableur CSV</a>
			<a class="btn btn-info btn-small" href="<?php echo $this->url('inventaire', array('action'=>'listing'));?>"><i class="icon-th-list icon-white"></i> Afficher toutes les colonnes</a>
			</div>
		</span>
	</div>
</div>
<p>&nbsp;</p>
<?php 
}
?>