<?php
// module/Inventaire
define("__LOCALE__","fr_FR");
$this->plugin("currencyformat")->setCurrencyCode("EUR")->setLocale(__LOCALE__);

if (!isset($titre)) $titre = 'Mon inventaire';

?>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<head>
<style type="text/css">
@page {margin-top: 1cm;margin-left: 1cm;margin-bottom:3cm;margin-right: 1cm;}
body {font:10pt helvetica;}
h1, h2, h3, h4 {font-family:helvetica;}
p {margin:0 0 3 0;}
.photo {display:block;float:left;}
.label {background:#f0f0f0;color:#555555;font-size: 7pt;width:85pt;}
table.table-content {
	width:100%;
}
.content {font-size: 8pt;}
.hero-unit{display:block;padding:3pt;margin:2pt;margin-bottom:10pt;border-bottom:1pt solid gray;}
.hero-unit h1, .hero-unit h2, .hero-unit h3, .hero-unit h4 {margin:0px;line-height:0.8;letter-spacing:-1pt;}
.hero-unit h1 {margin-bottom:6pt;font-size:25pt;}
.hero-unit h2 {margin-bottom:5pt;font-size:20pt;}
.hero-unit h3 {margin-bottom:4pt;font-size:17pt;}
.hero-unit h4 {margin-bottom:3pt;font-size:14pt;}
.hero-unit p{font-size:10pt;line-height:10pt;}
#page-de-titre {font-size:7pt;}
#page-de-titre .placeholder {background:#f5f5f5;margin-top:2pt;margin-bottom:2pt;padding:5pt;height:1.5cm;}
#page-de-titre DIV {width:4.2cm;}
#page-de-titre H3 {color:#f5f5f5;font-size:9pt;line-height:5pt;margin:0pt;padding:0pt;}
#page-de-titre H4.surtitre {color:#d5d5d5;font-size:18pt;line-height:7pt;letter-spacing:3pt;margin:0pt;padding:0pt;}
#page-de-titre #titre {position:absolute;top:4cm;left:5cm;width:9cm;font-size:9pt;}
#page-de-titre #titre H1 {color:#68B604;}
#page-de-titre #dates-registre {position:absolute;top:12cm;left:5cm;width:9cm;font-size:9pt;}
#page-de-titre #dates-registre H3,
#page-de-titre #dates-registre H4 {display:none;}
#page-de-titre #nom-adresse-musee {position:absolute;bottom:0cm;left:0cm;}
#page-de-titre #nom-adresse-personnemorale {position:absolute;bottom:0cm;left:4.75cm;}
#page-de-titre #lieu-conservation {position:absolute;bottom:0cm;left:9.45cm;}
#page-de-titre #paraphe-responsable-scientifique {position:absolute;bottom:0cm;left:14.2cm;}
.center {text-align:center;}
.fin-impression {background:gray;text-align:right;color:white;font-size:7pt;}
.page-break {page-break-before: always;}
</style>
</head>
<body>

<script type="text/php">
    if ( isset($pdf) ) {
        $font = Font_Metrics::get_font("JosefinSans");
		$mm2coords = 2.835;
        $pdf->page_text(194 * $mm2coords, 282 * $mm2coords, "{PAGE_NUM}/{PAGE_COUNT}", $font, 8, array(0,0,0));

		$x = 28;
		$y = 20;
		$size = 8;
		$font = Font_Metrics::get_font("JosefinSans");
		$color = array(0,0,0);
		$line_height = $pdf->get_font_height($font, $size) + 3;

		$longtext = utf8_encode("L'application Inventaire est actuellement en cours de développement et vise à offrir un programme complémentaire à CollectiveAccess pour gérer l'inventaire des collections. Les recommandations du Service des Musées de France sont en cours d'implémentation dans ce programme. Pour toute information, merci de nous contacter par email à contact@ideesculture.com.");
		$lines = array(
			'Application Inventaire - <?php print $titre; ?>' 
		);

		$linetext = '';
		while (strlen($longtext) > 0) {
			while ($pdf->get_text_width($linetext, $font, $size) < (520-($x*2)) && strlen($longtext) > 0) {
				if ($pdf->get_text_width($linetext . substr($longtext, 0, strpos($longtext, ' ')+1), $font, $size) > (520-($x*2))) { break; }
				$linetext .= substr($longtext, 0, strpos($longtext, ' ')+1);
				$longtext = substr($longtext, strpos($longtext, ' ')+1);
			}
			$lines[] = $linetext;
			$linetext = '';
		}

		while ($line = array_shift($lines)) {
			$line_y = 815 - $y - ( $line_height * count($lines));
			// Note : $pdf->page_text envoie le texte sur toutes les pages, $pdf->text envoie le texte sur la page en cours
			$pdf->page_text($x, $line_y, $line, $font, $size, $color);
		}
	}
</script>
<?php 
$this->headTitle($titre);
?>
<!--
<div id="page-de-titre">
	<div id="titre">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-inventaire/titre.html");
		?>
	</div>
	<div id="dates-registre">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-commun/dates-registre.html");
		?>
	</div>
	<div id="nom-adresse-musee">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-commun/nom-adresse-musee.html");
		?>
	</div>
	<div id="nom-adresse-personnemorale">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-commun/nom-adresse-personnemorale.html");
		?>
	</div>
	<div id="lieu-conservation">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-inventaire/lieu-conservation.html");
		?>
	</div>
	<div id="paraphe-responsable-scientifique">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-inventaire/paraphe-responsable-scientifique.html");
		?>
	</div>
</div>

<div class="page-break"></div>
-->
<!-- page blanche en dos de page de titre -->

<!--
<div id="pages-liminaires">
	<div id="contenu">
		<?php 
		include(__DIR__."/../../../../../public/files/editions/insertions-pdf-inventaire/pages-liminaires.html");
		?>
	</div>
</div>

<div class="page-break"></div>
-->
<!-- page blanche après les pages liminaires -->

<?php
$labels = array("numinv" => "Numéro d'inventaire");
foreach ($inventaires as $inventaire) { ?>
	<div class="hero-unit">
    	<div style="clear:both; position:relative;">
				<table class="table-content">
				<tr><td class="label">Numéro d'inventaire</td><td></td>
				<?php if($inventaire->file != "") : ?>
					<td class="label" rowspan="10">
					<img src="<?php print $imagepath; ?>/files/assets/<?php print $inventaire->file; //1 ?>" style="width:120pt;">
					</td></tr>
				<?php $csimg = "colspan=\"2\""; 
				endif; ?>
				<tr><td colspan="2"><h4><?php print $inventaire->numinv_display; //1 ?></h4></td></tr>
				<tr><td class="label">Désignation</td><td class="content"><?php print $inventaire->designation; //8?></td></tr>
				<tr><td class="label">Mode d'acquisition</td><td class="content"><?php print $inventaire->mode_acquisition; //2?></td></tr>
				<tr><td class="label">Date d'acquisition</td><td class="content"><?php print $inventaire->date_acquisition; ?></td></tr>    		
				<tr><td class="label">Donateur</td><td class="content"><?php print $inventaire->donateur; //3?></td></tr>
				<tr><td class="label">Prix</td><td class="content"><?php print $inventaire->prix; //6 ?></td></tr>
				<tr><td class="label">Avis</td><td class="content"><?php print $inventaire->avis; //5?></td></tr>
				<tr><td class="label">Inscription</td><td class="content"><?php print $inventaire->inscription; //9?></td></tr>
				<tr><td class="label">Date d'inscription</td><td class="content"><?php print $inventaire->date_inscription; //7 ?></td></tr> 
				<tr><td class="label">Matériaux</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->materiaux; //10?></td></tr>
				<tr><td class="label">Techniques</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->techniques; //11?></td></tr>
				<tr><td class="label">Mesures</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->mesures; //12?></td></tr>
				<tr><td class="label">Etat</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->etat; //13?></td></tr>
				<tr><td class="label">Auteur</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->auteur; //14 ?></td></tr>
				<tr><td class="label">Epoque</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->epoque; //15 ?></td></tr>
				<tr><td class="label">Usage</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->usage; //16 ?></td></tr>
				<tr><td class="label">Provenance</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->provenance; //17 ?></td></tr>
				<tr><td class="label">Observations</td><td class="content" <?php print $csimg; ?>><?php print $inventaire->observations; //18 ?></td></tr>
				</table>
		</div>
	</div>
<?php 
}
?>
<p class="fin-impression">
	fin de l'impression
</td></tr>

<div class="page-break"></div>

<!-- page blanche après la fin de l'impression -->

<div id="pages-libres-fin-registre">
<?php include(__DIR__."/../../../../../public/files/editions/insertions-pdf-commun/pages-blanches-fin-registre.html"); ?>
</div>