<?php
// module/Inventaire/view/inventaire/inventaire/index.phtml:

$title = 'Mon inventaire';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>

    <th>Numéro d'inventaire (1)</th>
    <th>Mode d'acquisition (2)</th>
    <th>Donateur (3)</th>
    <th>Date d'acquisition (4)</th>
    <th>Avis (5)</th>
    <th>Prix (6)</th>
    <th>Date d'inscription (7)</th>
    <th>Désignation (8)</th>
    <th>Inscription (9)</th>
    <th>Matériaux (10)</th>
    <th>Techniques (11)</th>
    <th>Mesures (12)</th>
    <th>Etat (13)</th>
    <th>Auteur (14)</th>
    <th>Epoque (15)</th>
    <th>Usage (16)</th>
    <th>Provenance (17)</th>
    <th>Observations (18)</th>
    <th>Validation</th>
</tr>
<?php print $page;?>
<?php foreach ($inventaires as $inventaire) : ?>
<tr>
    <td><?php echo $this->escapeHtml($inventaire->numinv); 										// 1 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->mode_acquisition); 							// 2 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->donateur); 									// 3 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->date_acquisition);							// 4 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->avis);										// 5 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->prix);										// 6 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->date_inscription);							// 7 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->designation);									// 8 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->inscription);									// 9 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->materiaux);									//10 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->techniques);									//11 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->mesures);										//12 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->etat);										//13 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->auteur);										//14 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->epoque);										//15 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->usage);										//16 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->provenance);									//17 ?></td>
    <td><?php echo $this->escapeHtml($inventaire->observations);								//18 ?></td>
    <td><?php echo ($this->escapeHtml($inventaire->validated) ? "validé" : "en attente");		?></td>

</tr>
<?php endforeach; ?>

</table>
<p>
    <a class="btn btn-info btn-large" href="<?php echo $this->url('inventaire', array());?>">Revenir à la liste des objets</a>
</p>
