<?php
// module/Inventaire/view/inventaire/inventaire/search.phtml:

$title = 'Recherche';
$this->headTitle($title);


?>
<div class="row">
	<div class="span6">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="span6">
		<span class="pull-right">
		<?php if ($auth["logged"]) { ?>
			<p>	
			<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(),array("img_size"=>24)) ?>
			<a href="/user"><?php print $auth["login"] ?></a>
			</p>
			<?php 
		} else {
			?>
			<p>
			Vous n'êtes pas identifié 
			<a class="btn btn-small btn-group btn-info" href="/">connexion</a>
			</p>
		<?php } ?>
		</span>
	</div>
</div>
<div class="row">
	<div class="span12">
		<table class="table">
		<tr>
		    <th><?php print $fieldsname["numinv"]; ?></th>
		    <th><?php print $fieldsname["designation"]; ?></th>
		    <th><?php print $fieldsname["auteur"]; ?></th>
		    <th><span class="pull-right">Actions</span></th>
		</tr>
		<?php foreach ($inventaires as $inventaire) : ?>
		<tr>
		    <td>
			    <?php if ($inventaire->file) : ?>
				    <span style="width:36px;height:36px;background:transparent;display:inline-block;text-align:center;">
				    	<a href="<?php print "/inventaire/view/".$this->escapeHtml($inventaire->id);?>" alt="Afficher" title="Afficher">
				    	<img style="height:30px;" src="/files/assets/<?php print $inventaire->file; ?>" align="absmiddle">
				    	</a>
				    </span>
			    <?php else : ?>
			    	<span>
			    		<a href="<?php print "/photo/add/".$this->escapeHtml($inventaire->id);?>" alt="Ajouter une photo" title="Ajouter une photo"><img src="/images/icone-image.png"  style="width:36px;" align="absmiddle"></a>
			    	</span>
			    <?php endif; ?>
			    <a href="<?php print "/inventaire/view/".$this->escapeHtml($inventaire->id);?>" alt="Afficher" title="Afficher"> 
			    <?php echo $this->escapeHtml($inventaire->numinv);?>
			    </a>
		    </td>
			<td>
				<?php echo $this->escapeHtml($inventaire->designation);?>
			</td>
			<td>
				<?php echo $this->escapeHtml($inventaire->auteur);?>
			</td>
			<td>
				<span class="pull-right">
					<?php
			
					if($auth["logged"]) {
						// Si l'enregistrement n'est pas validé, on peut le modifier ou le valider
						if (!$inventaire->validated) { ?> 
				        	<a  class="btn btn-success btn-small" href="<?php echo $this->url('inventaire',
				            array('action'=>'delete', 'id' => $inventaire->id));?>">Retirer de la sélection</a>
							<a  class="btn btn-warning btn-small" href="<?php echo $this->url('inventaire',
							array('action'=>'validate', 'id' => $inventaire->id));?>">Inscrire à l'inventaire</a>
						<?php
						// Si l'enregistrement est validé, aucune modification possible
						} else { 
						?>
							<a  class="btn disabled btn-small">Retirer de la sélection</a>
							<a  class="btn disabled btn-small">Inscrire à l'inventaire</a>
						<?php 
						}
					}
					?>
				</span>
		    </td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td>
			<?php echo $this->paginationControl($inventaires,
                                    'Sliding',
                                    'inventaire/inventaire/my_pagination_control', array('action'=>'index'));?>
            </td>
			<?php if (count($yearsOptions)>2) :?>
            <td colspan="3">
            	<span class="pull-right">
				 <a class="btn btn-info btn-small" href="<?php print $this->url('inventaire');?>">Retour à l'inventaire</a>
				</span>
			</td>	
            <?php endif ?>
		</td></tr>
		</table>
	</div>
</div>
<?php 
if($auth["logged"]) {
?>
<div class="row">
	<div class="span6">
		<a class="btn btn-success btn-large" href="<?php echo $this->url('inventaire', array('action'=>'add'));?>">Ajouter un objet</a>
		<a class="btn btn-success btn-large" href="<?php echo $this->url('inventaire', array('action'=>'listingExportPdf'));?>">Générer le PDF</a>
		<a class="btn btn-info btn-large" href="<?php echo $this->url('photo', array('action'=>'index'));?>">Afficher les photos</a>
	</div>
	<div class="span6">
		<span class="pull-right">
			<a class="btn btn-success btn-small" href="<?php echo $this->url('inventaire', array('action'=>'listingExportCSV'));?>">Export tableur CSV</a>
			<a class="btn btn-info btn-small" href="<?php echo $this->url('inventaire', array('action'=>'listing'));?>">Afficher toutes les colonnes</a>
		</span>
	</div>
</div>
<?php 
}
?>