<?php
// module/Inventaire/view/inventaire/inventaire/validate.phtml:

$title = "Inscrire à l'inventaire";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes vous sur de vouloir inscrire l'objet à l'inventaire l'objet suivant ?</p>
<p>
	Numéro d'inventaire : <b><?php echo $this->escapeHtml($inventaire->numinv_display); ?></b>
</p>
<p>
	<?php echo $inventaire->designation; ?>
</p>

<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><b>Date d'inscription</b> La date d'inscription à l'inventaire définie dans la base CollectiveAccess va être redéfinie à la date du jour de validation (<?php print date("d/m/Y"); ?>).</p>
</div>
<div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><b>Modification définitive</b> Après inscription, l'objet ne sera plus modifiable.</p>
</div>

<?php
$url = $this->url('inventaire', array(
    'action' => 'validate',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $inventaire->id; ?>" />
    <button class="btn btn-warning" type="submit" name="validate" value="Yes">Inscrire à l'inventaire</button>
    <button class="btn btn-info" type="submit" name="validate" value="No">Annuler</button>
</div>
</form>
