<?php
define("__LOCALE__","fr_FR");
$this->plugin("currencyformat")->setCurrencyCode("EUR")->setLocale(__LOCALE__);

// module/Inventaire/view/inventaire/inventaire/view.phtml:

$title = 'Afficher un objet';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
	<div class="span12">
		<table class="table">
		<tr><td>
		<?php if(isset($photo->file)) :?>
			<span style="float:right;">
			<img style="width:300px;" src="/files/assets/<?php print $this->escapeHtml($photo->file); //1 ?>">
			<p>
			<?php print $photo->credits;?>
			</p>
			<p class="btn-group pull-right">
			<a  class="btn btn-small btn-success" href="<?php echo $this->url('photo',
				array('action'=>'edit', 'id' => $photo->id));?>"><i class="icon-pencil icon-white"></i> Modifier</a>
			<a  class="btn btn-small btn-warning" href="<?php echo $this->url('photo',
				array('action'=>'delete', 'id' => $photo->id));?>"><i class="icon-remove icon-white"></i> Supprimer</a>
			</p>
			</span>
		<?php endif ?>
		<?php foreach($fields as $field) {
			print "<p><b>".$fieldsname[$field]."</b> : ";
			if (!strtotime($inventaire->$field)) {
				print $this->escapeHtml($inventaire->$field);
			} else {
				print $this->dateFormat(new DateTime($inventaire->$field), IntlDateFormatter::LONG, IntlDateFormatter::NONE, __LOCALE__); 
			}
			print "</p>\n";
		}
		;?>
		</td></tr>
		</table>
	</div>
</div>
<div class="row">
	<div class="span12">
		<p class="btn-group">
		    <a class="btn btn-info" href="<?php echo $this->url('inventaire', array());?>">Revenir à la liste des objets</a>
		    <?php if (!$inventaire->validated && $auth["logged"]) : ?> 
				<a  class="btn btn-success" href="<?php echo $this->url('inventaire',
				array('action'=>'edit', 'id' => $inventaire->id));?>"><i class="icon-pencil icon-white"></i> Modifier</a>
				<a  class="btn btn-warning" href="<?php echo $this->url('inventaire',
				array('action'=>'delete', 'id' => $inventaire->id));?>"><i class="icon-remove icon-white"></i> Supprimer</a>
				<a  class="btn btn-warning" href="<?php echo $this->url('inventaire',
				array('action'=>'validate', 'id' => $inventaire->id));?>"><i class="icon-check icon-white"></i> Valider</a>
			<?php endif; ?>
			<?php if ($inventaire->ca_id) : ?>
			<a  class="btn btn-success" 
							href="<?php echo $config_ca_direct["url"]."/index.php/editor/objects/ObjectEditor/Summary/object_id/".$inventaire->ca_id; ?>" 
							title="Afficher dans CA"><i class="icon-share icon-white"></i> Afficher dans CA</a>
			<?php endif; ?>
		</p>
	</div>
</div>
