<?php
define("__LOCALE__","fr_FR");
$this->plugin("currencyformat")->setCurrencyCode("EUR")->setLocale(__LOCALE__);

// module/Inventaire/view/inventaire/inventaire/view.phtml:

$title = 'Afficher un objet';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
	<div class="span12">
		<table class="table">
		<tr><td>
		<?php if(isset($photo->file)) :?>
			<span style="float:right;"><img style="width:300px;" src="/files/assets/<?php print $this->escapeHtml($photo->file); //1 ?>"></span>
		<?php endif ?>
		<?php foreach($fields as $field) {
			print "<p><b>".$fieldsname[$field]."</b> : ";
			if (!strtotime($inventaire->$field)) {
				print $this->escapeHtml($inventaire->$field);
			} else {
				print $this->dateFormat(new DateTime($inventaire->$field), IntlDateFormatter::LONG, IntlDateFormatter::NONE, __LOCALE__); 
			}
			print "</p>\n";
		}
		;?>
		</td></tr>
		</table>
	</div>
</div>
<div class="row">
	<div class="span12">
		<p class="btn-group">
		    <a class="btn btn-info" href="<?php echo $this->url('inventaire', array());?>">Revenir à la liste des objets</a>
		    <?php if (!$depot->validated) { ?> 
				<a  class="btn btn-success" href="<?php echo $this->url('depot',
				array('action'=>'edit', 'id' => $depot->id));?>"><i class="icon-pencil icon-white"></i> Modifier</a>
				<a  class="btn btn-success" href="<?php echo $this->url('depot',
				array('action'=>'delete', 'id' => $depot->id));?>"><i class="icon-remove icon-white"></i> Supprimer</a>
				<a  class="btn btn-warning" href="<?php echo $this->url('depot',
				array('action'=>'validate', 'id' => $depot->id));?>"><i class="icon-check icon-white"></i> Valider</a>
			<?php } ?>
		</p>
	</div>
</div>
