<div class="hero-unit">
	<img src="../../images/erreur.png" align=left>
	<h1>Erreur</h1>
	<p><?php echo $this->translate($this->message) ?></p>
	<p><a class="btn btn-success btn-large" href="<?php print $this->url("application"); ?>" target="_blank"><?php echo $this->translate("Retourner à la page d'accueil") ?> &raquo;</a></p>
</div>


<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php 
	$e = $this->exception->getPrevious();
	if(isset($this->exception) && $this->exception instanceof Exception): ?>

<hr/>

            <div class="tabbable">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#lA" data-toggle="tab"><?php echo $this->translate('Message') ?></a></li>
                <li><a href="#lB" data-toggle="tab"><?php echo $this->translate('Additional information') ?></a></li>
                <?php if ($e) : ?>
                <li><a href="#lC" data-toggle="tab"><?php echo $this->translate('Previous exceptions') ?></a></li>	
                <?php endif; ?>
              </ul>
              
              <div class="tab-content">
              	<!--  Message  -->
                <div class="tab-pane active" id="lA">
                  <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                </div>
                
                <!--  Additionnal information -->
                <div class="tab-pane" id="lB">
					<h3><?php echo get_class($this->exception); ?></h3>
				<dl>
				    <dt><?php echo $this->translate('File') ?> :</dt>
				    <dd>
				        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
				    </dd>
				    <dt><?php echo $this->translate('Message') ?>:</dt>
				    <dd>
				        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
				    </dd>
				    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
				    <dd>
				        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
					    </dd>
					</dl>
				</div>
                <div class="tab-pane" id="lC">
                	<?php if ($e) : ?>
                		<?php while($e) : ?>
					    <li>
					        <h3><?php echo get_class($e); ?></h3>
					        <dl>
					            <dt><?php echo $this->translate('File') ?>:</dt>
					            <dd>
					                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
					            </dd>
					            <dt><?php echo $this->translate('Message') ?>:</dt>
					            <dd>
					                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
					            </dd>
					            <dt><?php echo $this->translate('Stack trace') ?>:</dt>
					            <dd>
					                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
					            </dd>
					        </dl>
					    </li>
					    <?php
					        $e = $e->getPrevious();
					        endwhile;
					    ?>
				    <?php endif; ?>
                </div>
              </div>
            </div> <!-- /tabbable -->
 
<?php else: ?>

<h3><?php echo $this->translate('No Exception available') ?></h3>

<?php endif ?>

<?php endif ?>
