<?php 

// filename : module/Test/view/test/photo/add.phtml
$form = $this->form;
$inventaire_id = $this->inventaire_id;
$id = $this->id;
$form->setAttribute('action', "/photo/add/$inventaire_id");
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('inventaire_id'));
echo $this->formRow($form->get('credits'));
echo $this->formRow($form->get('file'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>