<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Inventaire'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/images/favicon.png'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/docs.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        				->prependStylesheet($this->basePath() . '/css/datepicker.css') ?>
		<!-- Le styles -->
	    <!-- 
	    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
	    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
	    <link href="http://twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet">
	     -->
	
	    <!-- Le fav and touch icons -->
	    <link rel="shortcut icon" href="assets/ico/favicon.ico">
	    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
	    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
	    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
	    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
	        
        <!-- Scripts -->
        <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->appendFile($this->basePath() . '/js/jquery.js')
                                      ->appendFile($this->basePath() . '/js/bootstrap.js')
                                      ->appendFile($this->basePath() . '/js/bootstrap-datepicker.js')
         ?> 

    </head>
    <body data-spy="scroll" data-target=".bs-docs-sidebar">
        <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <div class="container">
                 	<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <!--  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> -->
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    <!-- </a> -->
                    </button>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Inventaire') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li <?php print ($this->url() == "/" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Accueil'); ?></a></li>
                            <li <?php print ($this->url() == "/inventaire" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('inventaire') ?>"><?php echo $this->translate('Inventaire des collections'); ?></a></li>
                            <li <?php print ($this->url() == "/search" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('search') ?>"><?php echo $this->translate('Recherche'); ?></a></li>
                            <li <?php print ($this->url() == "/photo" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('photo') ?>"><?php echo $this->translate('Photos'); ?></a></li>
                            <li <?php print ($this->url() == "/editions" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('editions') ?>"><?php echo $this->translate('Editions'); ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        
        <?php if ($this->jumbotron) : ?>
        <!-- Subhead
		================================================== -->
		<header class="jumbotron subhead" id="overview">
		  <div class="container">
		    <?php echo $this->jumbotron; ?>
		  </div>
		</header>        
        <?php endif; ?>
    
        <div class="container">
        	<?php echo $this->content; ?>
        	<p>&nbsp;</p>
            <footer>
                <p><a href="http://www.ideesculture.com">idéesculture</a>, 2012.  

		</p>
		
		
		</footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript(); 
        ?>
		<!-- Le javascript
	    ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster -->
	    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.js"></script>
	    <!-- <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-transition.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-scrollspy.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-button.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-collapse.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-carousel.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js"></script>
	    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-affix.js"></script> -->
	    <script src="http://twitter.github.com/bootstrap/assets/js/application.js"></script>
	    <script src="http://www.eyecon.ro/bootstrap-datepicker/js/google-code-prettify/prettify.js"></script>
    <script src="http://www.eyecon.ro/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>

    </body>
</html>
