<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Inventaire'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/images/favicon.png'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Inventaire') ?></a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li <?php print ($this->url() == "/" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Accueil'); ?></a></li>
                            <li <?php print ($this->url() == "/inventaire" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('inventaire') ?>"><?php echo $this->translate('Inventaire des collections'); ?></a></li>
                            <li <?php print ($this->url() == "/search" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('search') ?>"><?php echo $this->translate('Recherche'); ?></a></li>
                            <li <?php print ($this->url() == "/photo" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('photo') ?>"><?php echo $this->translate('Photos'); ?></a></li>
                            <li <?php print ($this->url() == "/editions" ? "class=\"active\"" : "") ?>><a href="<?php echo $this->url('editions') ?>"><?php echo $this->translate('Editions'); ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><a href="http://www.ideesculture.com">idéesculture</a>, 2012. 

		</p>
		</footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript(); 
        ?>
    </body>
</html>
