<?php
// module/Inventaire/view/inventaire/depot/delete.phtml:

$title = 'Supprimer un objet';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes vous sur de vouloir supprimer
    <b><?php echo $this->escapeHtml($depot->designation); ?></b>, correspondant au numéro d'depot
    <b><?php echo $this->escapeHtml($depot->numinv); ?></b> ?
</p>
<p>Cette modification est définitive.</p>
<?php
$url = $this->url('depot', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $depot->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>