<?php
// module/Depot/view/depot/depot/index.phtml:

$title = 'Les dépôts';
$this->headTitle($title);

?>
<div class="row">
	<div class="span6">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="span6">
		<span class="pull-right">
		<?php if ($auth["logged"]) { ?>
			<p>	
			<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(),array("img_size"=>24)) ?>
			<a href="/user"><?php print $auth["login"] ?></a>
			</p>
			<?php 
		} else {
			?>
			<p>
			Vous n'êtes pas identifié 
			<a class="btn btn-small btn-info" href="/">connexion</a>
			</p>
		<?php } ?>
		</span>
	</div>
</div>

<div class="row">
	<div class="span12">
		<table class="table">
		<tr>
		    <th><?php print $fieldsname["numdep"]; ?></th>
		    <th><?php print $fieldsname["designation"]; ?></th>
		    <th><?php print $fieldsname["auteur"]; ?></th>
		    <th><span class="pull-right">Actions</span></th>
		</tr>
		<?php foreach ($depots as $depot) : ?>
		<tr>
		    <td>
			    <?php //if ($depot->file) : ?><!-- 
				    <span style="width:36px;height:36px;background:transparent;display:inline-block;text-align:center;">
				    	<a href="<?php print "/depot/view/".$this->escapeHtml($depot->id);?>" alt="Afficher" title="Afficher">
				    	<img style="height:30px;" src="/files/assets/<?php print $depot->file; ?>" align="absmiddle">
				    	</a>
				    </span>
			    <?php //else : ?> -->
			    	<span>
			    		<a href="<?php print "/photo/add/".$this->escapeHtml($depot->id);?>" alt="Ajouter une photo" title="Ajouter une photo"><img src="/images/icone-image.png"  style="width:36px;" align="absmiddle"></a>
			    	</span>
			    <?php //endif; ?>
			    <a href="<?php print "/depot/view/".$this->escapeHtml($depot->id);?>" alt="Afficher" title="Afficher"> 
			    <?php echo $this->escapeHtml($depot->numinv);?>
			    </a>
		    </td>
			<td>
				<?php echo $this->escapeHtml($depot->designation);?>
			</td>
			<td>
				<?php echo $this->escapeHtml($depot->auteur);?>
			</td>
			<td>
				<span class="pull-right">
					<div class="btn-group">
					<?php
					if($auth["logged"]) {
						// Si l'enregistrement n'est pas validé, on peut le modifier ou le valider
						if (!$depot->validated) { ?> 
							<a  class="btn btn-success btn-small" href="<?php echo $this->url('depot',
							array('action'=>'edit', 'id' => $depot->id));?>" title="Modifier"><i class="icon-pencil icon-white"></i></a>
				        	<a  class="btn btn-success btn-small" href="<?php echo $this->url('depot',
				            array('action'=>'delete', 'id' => $depot->id));?>" title="Supprimer"><i class="icon-remove icon-white"></i></a>
							<a  class="btn btn-warning btn-small" href="<?php echo $this->url('depot',
							array('action'=>'validate', 'id' => $depot->id));?>" title="Valider"><i class="icon-check icon-white"></i></a>
						<?php
						// Si l'enregistrement est validé, aucune modification possible
						} else { 
						?>
							<a  class="btn disabled btn-small" title="Modifier"><i class="icon-pencil icon-white"></i></a>
							<a  class="btn disabled btn-small" title="Supprimer"><i class="icon-remove icon-white"></i></a>
							<a  class="btn disabled btn-small" title="Valider"><i class="icon-check icon-white"></i></a>
						<?php 
						}
					}
					?>
					</div>
				</span>
		    </td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td>
			<?php echo $this->paginationControl($depots,
                                    'Sliding',
                                    'depot/depot/my_pagination_control', array('route'=>'depot','action'=>'index'));?>
            </td>
            <td colspan="3">
            <?php if (count($yearsOptions)>2) :?>
            	<span class="pull-right">
				 <div class="btn-group"><a class="btn btn-info btn-small" href="<?php print $this->url('depot');?>">Toutes les années</a>
				<?php foreach($yearsOptions as $option) : ?>
					<?php if((isset($option["disabled"]) && (!$option["disabled"]))) : ?> 
						<a class="btn btn-info btn-small" href="<?php print $this->url('depot', array('action'=>'index', 'annee'=> $option["label"]));?>"><?php print $option["label"] ?></a> 
					<?php endif ?>
				<?php endforeach ?>
				</div>
				</span>
            <?php endif ?>
			</td>	
        </td></tr>
		</table>
	</div>
</div>
<?php 
if($auth["logged"]) {
?>
<div class="row">
	<div class="span6">
		<div class="btn-group">
		<a class="btn btn-success btn-large" href="<?php echo $this->url('depot', array('action'=>'add'));?>">Ajouter un objet</a>
		<a class="btn btn-success btn-large" href="<?php echo $this->url('depot', array('action'=>'listingExportPdf'));?>">Générer le PDF</a>
		<a class="btn btn-info btn-large" href="<?php echo $this->url('photo', array('action'=>'index'));?>">Afficher les photos</a>
		</div>
	</div>
	<div class="span6">
		<span class="pull-right">
			<div class="btn-group">
			<a class="btn btn-success btn-small" href="<?php echo $this->url('depot', array('action'=>'listingExportCSV'));?>">Export tableur CSV</a>
			<a class="btn btn-info btn-small" href="<?php echo $this->url('depot', array('action'=>'listing'));?>">Afficher toutes les colonnes</a>
			</div>
		</span>
	</div>
</div>
<?php 
}
?>