<?php
// module/Depot/view/depot/depot/index.phtml:

$title = 'Mon depot';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); 

var_dump($depots);
die();?></h1>

<table class="table">
<tr>

    <th>Numéro d'depot (1)</th>
    <th>Mode d'acquisition (2)</th>
    <th>Donateur (3)</th>
    <th>Date d'acquisition (4)</th>
    <th>Avis (5)</th>
    <th>Prix (6)</th>
    <th>Date d'inscription (7)</th>
    <th>Désignation (8)</th>
    <th>Inscription (9)</th>
    <th>Matériaux (10)</th>
    <th>Techniques (11)</th>
    <th>Mesures (12)</th>
    <th>Etat (13)</th>
    <th>Auteur (14)</th>
    <th>Epoque (15)</th>
    <th>Usage (16)</th>
    <th>Provenance (17)</th>
    <th>Observations (18)</th>
    <th>Validation</th>
</tr>
</table>

<?php 

<h1>Example</h1>
<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $item): ?>
  <li><?php echo $item; ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'my_pagination_control', array('route' => 'application/paginator')); ?>

<?php 


/* ?>
<?php foreach ($depots as $depot) : ?>
<tr>
    <td><?php echo $this->escapeHtml($depot->numinv); 										// 1 ?></td>
    <td><?php echo $this->escapeHtml($depot->mode_acquisition); 							// 2 ?></td>
    <td><?php echo $this->escapeHtml($depot->donateur); 									// 3 ?></td>
    <td><?php echo $this->escapeHtml($depot->date_acquisition);							// 4 ?></td>
    <td><?php echo $this->escapeHtml($depot->avis);										// 5 ?></td>
    <td><?php echo $this->escapeHtml($depot->prix);										// 6 ?></td>
    <td><?php echo $this->escapeHtml($depot->date_inscription);							// 7 ?></td>
    <td><?php echo $this->escapeHtml($depot->designation);									// 8 ?></td>
    <td><?php echo $this->escapeHtml($depot->inscription);									// 9 ?></td>
    <td><?php echo $this->escapeHtml($depot->materiaux);									//10 ?></td>
    <td><?php echo $this->escapeHtml($depot->techniques);									//11 ?></td>
    <td><?php echo $this->escapeHtml($depot->mesures);										//12 ?></td>
    <td><?php echo $this->escapeHtml($depot->etat);										//13 ?></td>
    <td><?php echo $this->escapeHtml($depot->auteur);										//14 ?></td>
    <td><?php echo $this->escapeHtml($depot->epoque);										//15 ?></td>
    <td><?php echo $this->escapeHtml($depot->usage);										//16 ?></td>
    <td><?php echo $this->escapeHtml($depot->provenance);									//17 ?></td>
    <td><?php echo $this->escapeHtml($depot->observations);								//18 ?></td>
    <td><?php echo ($this->escapeHtml($depot->validated) ? "validé" : "en attente");		?></td>

</tr>
<?php endforeach; ?>

</table> */ ?>
<p>
    <a class="btn btn-info btn-large" href="<?php echo $this->url('depot', array());?>">Revenir à la liste des objets</a>
</p>
