<?php
// module/Depot/view/depot/depot/index.phtml:

$title = 'Biens déposés';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>

    <th>en cours de développement</th>
</tr>
<?php print $page;?>
<?php foreach ($depots as $depot) : ?>
<tr>
    <td>...</td>

</tr>
<?php endforeach; ?>

</table>
<p>
    <a class="btn btn-info btn-large" href="<?php echo $this->url('depot', array());?>">Revenir à la liste des objets</a>
</p>
