<?php
// module/Depot/view/depot/depot/validate.phtml:

$title = 'Valider un objet';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes vous sur de vouloir valider
    <b><?php echo $this->escapeHtml($depot->designation); ?></b>, correspondant au numéro d'depot
    <b><?php echo $this->escapeHtml($depot->numinv); ?></b> ?
</p>
<p>Après validation, l'objet ne sera plus modifiable. Cette modification est définitive.</p>
<?php
$url = $this->url('depot', array(
    'action' => 'validate',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $depot->id; ?>" />
    <input type="submit" name="validate" value="Yes" />
    <input type="submit" name="validate" value="No" />
</div>
</form>
