<?php
// module/Inventaire/view/inventaire/inventaire/index.phtml:

$title = 'Recherche';
$this->headScript()->appendScript("
	    function toggle_visibility(id) {
	       var e = document.getElementById(id);
	       if(e.style.display == 'block')
	          e.style.display = 'none';
	       else
	          e.style.display = 'block';
	    }
		",
		$type = 'text/javascript');

$this->headTitle($title);



?>

<div class="row">
	<div class="span6">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="span6">
		<span class="pull-right">
		<?php if ($auth["logged"]) { ?>
			<p>	
			<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(),array("img_size"=>24)) ?>
			<a href="/user"><?php print $auth["login"] ?></a>
			</p>
			<?php 
		} else {
			?>
			<p>
			Vous n'êtes pas identifié 
			<a class="btn btn-small btn-info" href="/">connexion</a>
			</p>
		<?php } ?>
		</span>
	</div>
</div>

<div class="row">
	<div class="span12">
		<?php 
		
		$form = $this->form;
		$form->setAttribute('action', $this->url(
		    'search',
		    array(
		        'action' => 'index',
				'annee' => $year
		    )
		));
		$form->setAttribute('class', "form-inline");		
		$form->prepare();
		echo $this->form()->openTag($form)."\n";
		echo $this->formElement($form->get('numinv'))."\n";
		echo $this->formElement($form->get('designation'))."\n";
		echo $this->formElement($form->get('auteur'))."\n";
		echo $this->formSubmit($form->get('submit'))."\n";
		echo $this->form()->closeTag()."\n";
		?>
		<?php 
		?>
	</div>
</div>


<div class="row">
	<div class="span12">
		<table class="table">
		<tr>
		    <th><?php print $fieldsname["numinv"]; ?></th>
		    <th><?php print $fieldsname["designation"]; ?></th>
		    <th><?php print $fieldsname["auteur"]; ?></th>
		    <th><span class="pull-right">Actions</span></th>
		</tr>
		<?php foreach ($inventaires as $inventaire) : ?>
		<tr>
		    <td>
			    <?php if ($inventaire->file) : ?>
				    <span style="width:36px;height:36px;background:transparent;display:inline-block;text-align:center;">
				    	<a href="<?php print "/inventaire/view/".$this->escapeHtml($inventaire->id);?>" alt="Afficher" title="Afficher">
				    	<img style="height:30px;" src="/files/assets/<?php print $inventaire->file; ?>" align="absmiddle">
				    	</a>
				    </span>
			    <?php else : ?>
			    	<span>
			    		<a href="<?php print "/photo/add/".$this->escapeHtml($inventaire->id);?>" alt="Ajouter une photo" title="Ajouter une photo"><img src="/images/icone-image.png"  style="width:36px;" align="absmiddle"></a>
			    	</span>
			    <?php endif; ?>
			    <a href="<?php print "/inventaire/view/".$this->escapeHtml($inventaire->id);?>" alt="Afficher" title="Afficher"> 
			    <?php echo $this->escapeHtml($inventaire->numinv);?>
			    </a>
		    </td>
			<td>
				<?php echo $this->escapeHtml($inventaire->designation);?>
			</td>
			<td>
				<?php echo $this->escapeHtml($inventaire->auteur);?>
			</td>
			<td>
				<span class="pull-right">
					<div class="btn-group">
					<?php
					if($auth["logged"]) {
						// Si l'enregistrement n'est pas validé, on peut le modifier ou le valider
						if (!$inventaire->validated) { ?> 
							<a  class="btn btn-success btn-small" href="<?php echo $this->url('inventaire',
							array('action'=>'edit', 'id' => $inventaire->id));?>">Modifier</a>
				        	<a  class="btn btn-success btn-small" href="<?php echo $this->url('inventaire',
				            array('action'=>'delete', 'id' => $inventaire->id));?>">Supprimer</a>
							<a  class="btn btn-warning btn-small" href="<?php echo $this->url('inventaire',
							array('action'=>'validate', 'id' => $inventaire->id));?>">Valider</a>
						<?php
						// Si l'enregistrement est validé, aucune modification possible
						} else { 
						?>
							<a  class="btn disabled btn-small">Modifier</a>
							<a  class="btn disabled btn-small">Supprimer</a>
							<a  class="btn disabled btn-small">Valider</a>
						<?php 
						}
					}
					?>
					</div>
				</span>
		    </td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td>
			<?php echo $this->paginationControl($inventaires,
                                    'Sliding',
                                    'inventaire/inventaire/my_pagination_control', array('route'=>'search','action'=>'index'));?>
			</td>
            <td colspan="3">
			</td>	
        </td></tr>
		</table>
	</div>
</div>
<?php 
if($auth["logged"]) {
?>
<div class="row">
	<div class="span6">
		<div class="btn-group">
		<a class="btn btn-success btn-large" href="<?php echo $this->url('inventaire', array('action'=>'add'));?>">Ajouter un objet</a>
		<a class="btn btn-success btn-large" href="<?php echo $this->url('inventaire', array('action'=>'listingExportPdf'));?>">Générer le PDF</a>
		<a class="btn btn-info btn-large" href="<?php echo $this->url('photo', array('action'=>'index'));?>">Afficher les photos</a>
		</div>
	</div>
	<div class="span6">
		<span class="pull-right">
			<div class="btn-group">
			<a class="btn btn-success btn-small" href="<?php echo $this->url('inventaire', array('action'=>'listingExportCSV'));?>">Export tableur CSV</a>
			<a class="btn btn-info btn-small" href="<?php echo $this->url('inventaire', array('action'=>'listing'));?>">Afficher toutes les colonnes</a>
			</div>
		</span>
	</div>
</div>
<?php 
}
?>