<div class="row">
&nbsp;
</div>
<div class="row">

	<div class="span1">
	<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
	</div>
	<div class="span11">
	
		<h3><?php echo $this->zfcUserDisplayName() ?></h3>
		<?php if ($this->zfcUserIdentity()->getID() == 1) : ?>
		<p>
			<a class="btn btn-info" href="<?php echo $this->url('zfcuser/add') ?>">ajouter un utilisateur</a>
		</p>
		<?php endif; ?>
		<p>
			<a class="btn btn-primary" href="<?php echo $this->url('zfcuser/logout') ?>">déconnexion</a>
		</p>
		
	</div>
</div>
<div style="clear:both;"></div>
