<div class="bord-ronds-fond-blanc login">
<h2>Connexion</h2>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt>Login</dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt>Mot de passe</dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
        <?php endif ?>

        <dd><input type="submit" name="submit" value="Se connecter &raquo;" class="btn btn-info btn-large"></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>
</div>
<?php if ($this->enableRegistration) : ?>
Pas encore enregistré ? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
